In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
from bs4 import BeautifulSoup

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Deepshikha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
import praw
import pandas as pd

# Configure Reddit API credentials
reddit = praw.Reddit(
    client_id="get your client id from reddit developer portal",         # Replace with your client_id
    client_secret="get your client_secret from reddit developer portal", # Replace with your client_secret
    user_agent="MyScraper v1.0 by /u/financialdata"        # Replace with your user_agent
)

# Define the subreddit and data collection parameters
subreddit = reddit.subreddit("stocks")
post_limit = 50000  # Number of posts to fetch

# Initialize a list to hold the data
data = []

# Scrape posts
print("Scraping data from r/stocks...")
for post in subreddit.hot(limit=post_limit):  # Use 'hot', 'new', or 'top' as needed
    data.append({
        "Post ID": post.id,
        "Title": post.title,
        "Score": post.score,
        "Upvote Ratio": post.upvote_ratio,
        "Number of Comments": post.num_comments,
        "Created At": post.created_utc,  # UTC timestamp
        "Author": post.author.name if post.author else "Deleted",
        "Post URL": post.url,
        "Content": post.selftext  # The post body (text content)
    })

# Convert data to a pandas DataFrame
df = pd.DataFrame(data)

# Save data to a CSV file
csv_file = "reddit_stocks_data.csv"
df.to_csv(csv_file, index=False)

print(f"Scraping complete! Data saved to {csv_file}.")


In [107]:
df = pd.read_csv('reddit_stocks_data.csv')
df.head()

Post ID                                              Title  Score  \
0  1grtfyq  r/Stocks Daily Discussion & Fundamentals Frida...     25   
1  1h39vdi  /r/Stocks Weekend Discussion Saturday - Nov 30...      2   
2  1h3465k  Do you think Rivian would make it to $100 a sh...     67   
3  1h2roez  23-Hour Party People: U.S. stocks may soon tra...    407   
4  1h2nht8  Thoughts on buying BRB.K this month instead of...     56   

   Upvote Ratio  Number of Comments    Created At             Author  \
0          0.94                 477  1.731667e+09      AutoModerator   
1          1.00                   9  1.732963e+09      AutoModerator   
2          0.60                 258  1.732940e+09        CoolTomatoh   
3          0.92                 162  1.732903e+09     DecisionNo1902   
4          0.80                  51  1.732892e+09  Life-Ambition1432   

                                            Post URL  \
0  https://www.reddit.com/r/stocks/comments/1grtf...   
1  https://www.reddit.com/r/stocks/comments/1h39v...   
2  https://www.reddit.com/r/stocks/comments/1h346...   
3  https://www.reddit.com/r/stocks/comments/1h2ro...   
4  https://www.reddit.com/r/stocks/comments/1h2nh...   

                                             Content  
0  This is the daily discussion, so anything stoc...  
1  This is the weekend edition of our stickied di...  
2  With talks of Rivian saving VW, California kee...  
3  **23-Hour Party People:**  \n**U.S. stocks may...  
4  Does anyone have any thoughts on buying BRB.K ...

In [108]:
# Selecting the specified columns: 'Title', 'Upvote Ratio', 'Number of Comments', and 'Content'
selected_columns = ['Title', 'Upvote Ratio', 'Number of Comments', 'Content']
df = df[selected_columns]

# Display the first few rows of the new DataFrame
df.head()


Title  Upvote Ratio  \
0  r/Stocks Daily Discussion & Fundamentals Frida...          0.94   
1  /r/Stocks Weekend Discussion Saturday - Nov 30...          1.00   
2  Do you think Rivian would make it to $100 a sh...          0.60   
3  23-Hour Party People: U.S. stocks may soon tra...          0.92   
4  Thoughts on buying BRB.K this month instead of...          0.80   

   Number of Comments                                            Content  
0                 477  This is the daily discussion, so anything stoc...  
1                   9  This is the weekend edition of our stickied di...  
2                 258  With talks of Rivian saving VW, California kee...  
3                 162  **23-Hour Party People:**  \n**U.S. stocks may...  
4                  51  Does anyone have any thoughts on buying BRB.K ...

In [109]:
df.shape

(172, 4)

In [110]:
## Missing values
df.isnull().sum()

Title                 0
Upvote Ratio          0
Number of Comments    0
Content               0
dtype: int64

In [111]:
df['Upvote Ratio'].unique()

array([0.94, 1.  , 0.6 , 0.92, 0.8 , 0.71, 0.72, 0.87, 0.84, 0.35, 0.66,
       0.78, 0.88, 0.85, 0.69, 0.95, 0.54, 0.9 , 0.16, 0.32, 0.49, 0.76,
       0.91, 0.62, 0.86, 0.75, 0.97, 0.82, 0.47, 0.83, 0.33, 0.81, 0.45,
       0.77, 0.4 , 0.65, 0.73, 0.93, 0.56, 0.89, 0.59, 0.64, 0.42, 0.96,
       0.61, 0.79, 0.48, 0.43, 0.44, 0.41, 0.25, 0.29, 0.28, 0.7 , 0.53,
       0.67])

In [112]:
df['Number of Comments'].unique()

array([ 477,    9,  258,  162,   51,    4,   11,  159,  369,  173,   14,
        148,  115, 2319,   74,  118,   47,   86,    7,  364,   50,   34,
         32,   20,   18,  228,  262,   15,   45,   98,  175,   73,   43,
         13,  291,   41,   40,   26,  195,  233,  106,   19,   17,   52,
        357,  229,  108,   36,   44,   70,   27,    6,   23,  641,   12,
          8,  190,   57,    1,  174,  188,   30,   79,  284,  255,   39,
          0,   16,  109,  150,   46,  246,  351,   29,  431,   82,   61,
         28,  303,  142,   48,   38,   63,  151,  271,   93,  288,   22,
         68,   56,   67,   25,   88,    3,  141,  207,  348,   76,  385,
        110,   69,   35,  116,   84,  122,   65,   85], dtype=int64)

In [113]:
df['Number of Comments'].value_counts()

Number of Comments
4      8
9      6
7      6
11     5
8      4
      ..
357    1
52     1
19     1
106    1
85     1
Name: count, Length: 107, dtype: int64

In [114]:
df['Upvote Ratio'].value_counts()

Upvote Ratio
0.80    8
0.84    8
0.88    8
0.94    7
0.85    7
0.87    7
0.91    7
0.92    6
0.81    5
0.82    5
0.75    5
0.86    5
0.93    5
0.95    5
0.96    5
0.83    5
0.89    4
0.90    4
0.66    4
0.42    4
0.69    3
0.78    3
0.77    3
0.76    3
0.97    3
0.33    2
0.65    2
0.45    2
0.64    2
0.70    2
0.47    2
0.71    2
0.16    2
0.54    2
0.35    2
0.72    2
0.62    2
0.48    1
0.53    1
0.60    1
0.28    1
0.29    1
0.25    1
0.41    1
0.44    1
0.43    1
1.00    1
0.79    1
0.61    1
0.59    1
0.56    1
0.73    1
0.32    1
0.40    1
0.49    1
0.67    1
Name: count, dtype: int64

## Preprocessing and Cleaning

##### 1. Lower all the cases

In [115]:
df.columns
df['Title'] = df['Title'].str.lower()
df['Content'] = df['Content'].str.lower()
df.head(5)

Title  Upvote Ratio  \
0  r/stocks daily discussion & fundamentals frida...          0.94   
1  /r/stocks weekend discussion saturday - nov 30...          1.00   
2  do you think rivian would make it to $100 a sh...          0.60   
3  23-hour party people: u.s. stocks may soon tra...          0.92   
4  thoughts on buying brb.k this month instead of...          0.80   

   Number of Comments                                            Content  
0                 477  this is the daily discussion, so anything stoc...  
1                   9  this is the weekend edition of our stickied di...  
2                 258  with talks of rivian saving vw, california kee...  
3                 162  **23-hour party people:**  \n**u.s. stocks may...  
4                  51  does anyone have any thoughts on buying brb.k ...

In [116]:
## Clean data
#### 1. removing special characters

df['Content'] = df['Content'].apply(lambda x: re.sub(r'[^A-Z a-z 0-9\s]+', '', x))
df['Title'] = df['Title'].apply(lambda x: re.sub(r'[^A-Z a-z 0-9\s]+', '', x))

### 2. removing stop words
df['Content'] = df['Content'].apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords.words('english')]))
df['Title'] = df['Title'].apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords.words('english')]))

## 3. remove url
df['Content'] = df['Content'].apply(lambda x : re.sub(r'http\S+', '', x))
df['Title'] = df['Title'].apply(lambda x : re.sub(r'http\S+', '', x))

## 4. remove html tags
df['Content'] = df['Content'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
df['Title'] = df['Title'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())

## 5. remove extra spaces
df['Content'] = df['Content'].apply(lambda x: ' '.join(x.split()))
df['Title'] = df['Title'].apply(lambda x: ' '.join(x.split()))

In [117]:
df.head()

Title  Upvote Ratio  \
0  rstocks daily discussion fundamentals friday n...          0.94   
1    rstocks weekend discussion saturday nov 30 2024          1.00   
2                  think rivian would make 100 share          0.60   
3  23hour party people us stocks may soon trade n...          0.92   
4       thoughts buying brbk month instead dcaing sp          0.80   

   Number of Comments                                            Content  
0                 477  daily discussion anything stocks related fine ...  
1                   9  weekend edition stickied discussion thread dis...  
2                 258  talks rivian saving vw california keeping tax ...  
3                 162  23hour party people us stocks may soon trade n...  
4                  51  anyone thoughts buying brbk month one instead ...

##### Lemmatization

In [118]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Deepshikha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [119]:
lemmatizer = WordNetLemmatizer()

In [120]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [121]:
df['Content'] = df['Content'].apply(lambda x:lemmatize_words(x))

In [122]:
df['Title'] = df['Title'].apply(lambda x:lemmatize_words(x))

In [123]:
df.head()

Title  Upvote Ratio  \
0  rstocks daily discussion fundamental friday no...          0.94   
1    rstocks weekend discussion saturday nov 30 2024          1.00   
2                  think rivian would make 100 share          0.60   
3  23hour party people u stock may soon trade nea...          0.92   
4        thought buying brbk month instead dcaing sp          0.80   

   Number of Comments                                            Content  
0                 477  daily discussion anything stock related fine t...  
1                   9  weekend edition stickied discussion thread dis...  
2                 258  talk rivian saving vw california keeping tax c...  
3                 162  23hour party people u stock may soon trade nea...  
4                  51  anyone thought buying brbk month one instead u...

#### Data Segmentation based on comment and upvote

In [124]:

# Define a threshold for high engagement using the median of 'Comments' and 'Upvote Ratio'
comments_median = df['Number of Comments'].median()
upvote_median = df['Upvote Ratio'].median()

# Create a binary target column
df['Stock_Movement'] = np.where(
    (df['Number of Comments'] > comments_median) & (df['Upvote Ratio'] > upvote_median), 
    1,  # High engagement
    0   # Low engagement

)


In [125]:
df.head()

Title  Upvote Ratio  \
0  rstocks daily discussion fundamental friday no...          0.94   
1    rstocks weekend discussion saturday nov 30 2024          1.00   
2                  think rivian would make 100 share          0.60   
3  23hour party people u stock may soon trade nea...          0.92   
4        thought buying brbk month instead dcaing sp          0.80   

   Number of Comments                                            Content  \
0                 477  daily discussion anything stock related fine t...   
1                   9  weekend edition stickied discussion thread dis...   
2                 258  talk rivian saving vw california keeping tax c...   
3                 162  23hour party people u stock may soon trade nea...   
4                  51  anyone thought buying brbk month one instead u...   

   Stock_Movement  
0               1  
1               0  
2               0  
3               1  
4               0

In [126]:
df['Stock_Movement'].value_counts()

Stock_Movement
0    118
1     54
Name: count, dtype: int64

#### Train Test Split

In [127]:
from sklearn.model_selection import train_test_split
# Define features (X) and target (y) for the train-test split
X = df[['Content', 'Title']]  # Features: text-based columns
y = df['Stock_Movement']     # Target: binary column created earlier

# Perform train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Display the shapes of the resulting datasets
X_train.shape, X_test.shape, y_train.shape, y_test.shape


((137, 2), (35, 2), (137,), (35,))

In [131]:
# Combine 'Content' and 'Title' into a single text column
X_train_combined = X_train['Content'] + " " + X_train['Title']
X_test_combined = X_test['Content'] + " " + X_test['Title']



In [132]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the vectorizer
tfidf = TfidfVectorizer()

# Fit and transform the training data, and transform the testing data
X_train_tfidf = tfidf.fit_transform(X_train_combined)
X_test_tfidf = tfidf.transform(X_test_combined)

# Check the shapes of the resulting matrices
print("X_train_tfidf shape:", X_train_tfidf.shape)
print("X_test_tfidf shape:", X_test_tfidf.shape)


X_train_tfidf shape: (137, 5253)
X_test_tfidf shape: (35, 5253)


In [133]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow = bow.fit_transform(X_train_combined)
X_test_bow = bow.transform(X_test_combined)


In [134]:
X_train_bow.shape

(137, 5253)

In [140]:

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Initialize the model
model = MultinomialNB()

# Train the model
model.fit(X_train_tfidf, y_train)

# Make predictions
y_pred_tfidf = model.predict(X_test_tfidf)

# Confusion matrix
print(confusion_matrix(y_test,y_pred_tfidf))

# Evaluate the model
print("Accuracy for tfidf:", accuracy_score(y_test, y_pred_tfidf))


[[24  0]
 [11  0]]
Accuracy for tfidf: 0.6857142857142857


In [141]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Initialize the model
model = MultinomialNB()

# Train the model
model.fit(X_train_bow, y_train)

# Make predictions
y_pred_bow = model.predict(X_test_bow)

# Confusion Matrix
print(confusion_matrix(y_test,y_pred_bow))

# Evaluate the model
print("Accuracy for BOW:", accuracy_score(y_test, y_pred_bow))

[[21  3]
 [ 7  4]]
Accuracy for BOW: 0.7142857142857143
